# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boolean', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NestedA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boolean', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NestedB1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nested_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='views.NestedA')),
            ],
        ),
        migrations.CreateModel(
            name='NestedB2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nested_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='views.NestedA')),
            ],
        ),
        migrations.CreateModel(
            name='NestedC1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nested_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='views.NestedB1')),
            ],
        ),
        migrations.CreateModel(
            name='NestedC2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nested_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='views.NestedB1')),
            ],
        ),
        migrations.CreateModel(
            name='NestedC3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nested_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='views.NestedB2')),
            ],
        ),
    ]
