# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import panels.fields


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_auto_20161024_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='listdata',
            name='description',
            field=panels.fields.RichTextarea(blank=True),
        ),
        migrations.AlterField(
            model_name='listdata',
            name='select',
            field=models.CharField(choices=[(b'10', b'10'), (b'20', b'20'), (b'30', b'Dertig'), (b'40', b'40')], default=40, max_length=8),
        ),
    ]
