# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0003_auto_20161026_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='nesteda',
            name='global_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='views.GlobalA'),
        ),
        migrations.AddField(
            model_name='nestedb1',
            name='global_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='views.GlobalB'),
        ),
    ]
